# Generated by Django 4.1.7 on 2023-05-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='weight',
            field=models.DecimalField(decimal_places=100, max_digits=100, null=True),
        ),
    ]
