# Generated by Django 4.1.7 on 2023-05-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_quesmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='questionid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizid', models.IntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quesmodel')),
            ],
        ),
    ]
