# Generated by Django 4.1.7 on 2023-05-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_quesmodel_questionid_alter_quesmodel_weight_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('courseText', models.FileField(max_length=254, upload_to=None)),
                ('file_path', models.FilePathField(max_length=200)),
                ('time_duration', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lesson')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quesmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
