# Generated by Django 4.1.7 on 2023-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_file_delete_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='quizlink',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
