# Generated by Django 4.1.7 on 2023-05-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_rename_quizlink_video_quiz_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="quesmodel", name="questionid",),
        migrations.RemoveField(model_name="video", name="quiz_id",),
        migrations.AddField(
            model_name="quesmodel",
            name="lo",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(max_length=5000),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quesmodel",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.quiz"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.quiz"
            ),
        ),
    ]
